### ISSUE TITLE
Could you upgrade this to use Expo CLI 2?

### ISSUE THREAD

**Issue by estensen** [benawad/typescript-yarn-workspace-example#4]

**Comment by benawad** [comment]
Did it now work for you when you tried it with Expo CLI 2?

**Comment by estensen** [comment]
Nope, the upgrade is not going smoothly.

What I did:
On branch `1_add_ts_rn`
Install the new Expo CLI `npm install -g expo-cli`
Run `yarn build` from `typescript-yarn-workspace-example/`
Changed the Expo version to `30.0.0` in `app`
Changed the script command `exp` => `expo`
Run `yarn start`

Sometimes it renders the web UI, but most often it just crashes:
```
➜  app git:(1_add_ts_rn) ✗ yarn start
yarn run v1.10.1
$ expo start --offline
[12:10:34] Starting project at /Users/estensen/Developer/typescript-yarn-workspace-example/packages/app
[12:10:34] Expo DevTools is running at http://localhost:19002
[12:10:34] Opening DevTools in the browser... (press shift-d to disable)

/usr/local/lib/node_modules/expo-cli/node_modules/tree-kill/index.js:83
    ps.stdout.on('data', function (data) {
              ^
TypeError: Cannot read property 'on' of undefined
    at buildProcessTree (/usr/local/lib/node_modules/expo-cli/node_modules/tree-kill/index.js:83:15)
    at /usr/local/lib/node_modules/expo-cli/node_modules/tree-kill/index.js:104:11
    at Array.forEach (<anonymous>)
    at ChildProcess.onClose (/usr/local/lib/node_modules/expo-cli/node_modules/tree-kill/index.js:99:31)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:611:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by benawad** [comment]
here you go https://github.com/benawad/typescript-yarn-workspace-example/tree/expo-cli2

**Comment by estensen** [comment]
Thanks!
I still get the same error, but it's probably a global node module conflict.
